name: 'Nuve Platform Stop instance'
description: 'Stop a Nuve Platform instance'
author: 'Simone Gaffurini'
branding:
  icon: 'power'
  color: 'red'
inputs:
  email:
    description: Nuve Platform email
    required: true
  password:
    description: Nuve Platform password
    required: true
  instanceName:
    description: Name of the instance to shutdown
    required: true
  wait:
    description: Wait for shutdown
    required: false
    default: true
  timeout:
    description: Shutdown timeout (only if wait is set to true)
    required: false
    default: 600
runs:
  using: 'node20'
  main: 'dist/index.js'
